### ISSUE TITLE
[BUG]Crash: Create: Above And Beyond

### ISSUE THREAD

**Issue by BraveCaperCat** [Advanced-Rocketry/AdvancedRocketry#2299]
## Version of Advanced Rocketry
>2.0.0-12

## Have you verified this is an issue in the latest unstable build
- [x] N

## Version of LibVulpes
>1.0.2-25

## Version of Minecraft
>1.16.5

## Does this occur without other mods installed
- [x] N/A

## Crash report log
>[latest.log](https://github.com/Advanced-Rocketry/AdvancedRocketry/files/8193518/latest.log)

## Description of the problem
>Launch minecraft with Create: Above And Beyond
[Issue on modpack issue page](https://github.com/simibubi/Above-and-Beyond/issues/396)

**Comment by BraveCaperCat** [comment]
Do not lock issues, then if the "Solution" doesn't work then, i can't tell you, without another issue!

**Comment by BraveCaperCat** [comment]
[Unconfirmed Bug](https://github.com/Advanced-Rocketry/AdvancedRocketry/labels/Unconfirmed%20Bug)

**Comment by Silfryi** [comment]
This doesn't seem to be an us issue? You seem to have antique atlas somewhere its mixins don't apply. Like on the server side. I'm entirely unsure if AA is even _installable_ serverside. I'd guess not from this thing. Anyway, I don't see any of our code. Closing.

**Comment by BraveCaperCat** [comment]
> This doesn't seem to be an us issue? You seem to have antique atlas somewhere its mixins don't apply. Like on the server side. I'm entirely unsure if AA is even _installable_ serverside. I'd guess not from this thing. Anyway, I don't see any of our code. Closing.

It's a modpack, of course it can be installed on server-side (I am a great coder just don't know anything about Minecraft mods, that is why i know that term)

**Comment by BraveCaperCat** [comment]
And what is a "antique atlas somewhere its mixins"

**Comment by BraveCaperCat** [comment]
And it's 1.16.5 WHICH IT SAID IS BROKEN

**Comment by BraveCaperCat** [comment]
REOPEN

**Comment by BraveCaperCat** [comment]
I found something in the crash log:
java.lang.ClassNotFoundException

**Comment by BraveCaperCat** [comment]
at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:282) ~[modlauncher-8.0.9.jar:?]
		at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.0.9.jar:?]
		at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.0.9.jar:?]
		at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51]
		at java.lang.Class.forName0(Native Method) ~[?:1.8.0_51]
		at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_51]
		at cpw.mods.modlauncher.TransformerClassWriter.computeHierarchyFromFile(TransformerClassWriter.java:157) [modlauncher-8.0.9.jar:?]
		at cpw.mods.modlauncher.TransformerClassWriter.computeHierarchy(TransformerClassWriter.java:112) [modlauncher-8.0.9.jar:?]
		at cpw.mods.modlauncher.TransformerClassWriter.access$100(TransformerClassWriter.java:34) [modlauncher-8.0.9.jar:?]
		at cpw.mods.modlauncher.TransformerClassWriter$SuperCollectingVisitor.lambda$visit$0(TransformerClassWriter.java:185) [modlauncher-8.0.9.jar:?]
		at cpw.mods.modlauncher.TransformerClassWriter$SuperCollectingVisitor$$Lambda$539/1474607212.accept(Unknown Source) [modlauncher-8.0.9.jar:?]
		at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) [?:1.8.0_51]
		at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580) [?:1.8.0_51]
		at cpw.mods.modlauncher.TransformerClassWriter$SuperCollectingVisitor.visit(TransformerClassWriter.java:184) [modlauncher-8.0.9.jar:?]
		at org.objectweb.asm.tree.ClassNode.accept(ClassNode.java:372) [asm-tree-9.1.jar:9.1]
		at cpw.mods.modlauncher.TransformerClassWriter.computeHierarchy(TransformerClassWriter.java:99) [modlauncher-8.0.9.jar:?]
		at cpw.mods.modlauncher.TransformerClassWriter.getCommonSuperClass(TransformerClassWriter.java:59) [modlauncher-8.0.9.jar:?]
		at org.objectweb.asm.SymbolTable.addMergedType(SymbolTable.java:1202) [asm-9.1.jar:9.1]
		at org.objectweb.asm.Frame.merge(Frame.java:1299) [asm-9.1.jar:9.1]
		at org.objectweb.asm.Frame.merge(Frame.java:1197) [asm-9.1.jar:9.1]
		at org.objectweb.asm.MethodWriter.computeAllFrames(MethodWriter.java:1610) [asm-9.1.jar:9.1]
		at org.objectweb.asm.MethodWriter.visitMaxs(MethodWriter.java:1546) [asm-9.1.jar:9.1]
		at org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:769) [asm-tree-9.1.jar:9.1]
		at org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:649) [asm-tree-9.1.jar:9.1]
		at org.objectweb.asm.tree.ClassNode.accept(ClassNode.java:452) [asm-tree-9.1.jar:9.1]
		at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:133) [modlauncher-8.0.9.jar:?]
		at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) [modlauncher-8.0.9.jar:?]
		at cpw.mods.modlauncher.TransformingClassLoader.buildTransformedClassNodeFor(TransformingClassLoader.java:142) [modlauncher-8.0.9.jar:?]
		at cpw.mods.modlauncher.LaunchPluginHandler.lambda$null$8(LaunchPluginHandler.java:97) [modlauncher-8.0.9.jar:?]
		at cpw.mods.modlauncher.LaunchPluginHandler$$Lambda$458/1483008191.buildTransformedClassNodeFor(Unknown Source) [modlauncher-8.0.9.jar:?]
		at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.getClassNode(MixinLaunchPluginLegacy.java:222) [mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
		at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.getClassNode(MixinLaunchPluginLegacy.java:207) [mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
		at org.spongepowered.asm.mixin.transformer.ClassInfo.forName(ClassInfo.java:2005) [mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
		at org.spongepowered.asm.mixin.transformer.MixinInfo.getTargetClass(MixinInfo.java:1017) [mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
		at org.spongepowered.asm.mixin.transformer.MixinInfo.readTargetClasses(MixinInfo.java:1007) [mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
		at org.spongepowered.asm.mixin.transformer.MixinInfo.parseTargets(MixinInfo.java:895) [mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
		at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:867) [mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
		at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:779) [mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
		at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:539) [mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
		at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462) [mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
		at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438) [mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
		at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290) [mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
		at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) [mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
		at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) [mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
		at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) [mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
		at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:154) [modlauncher-8.0.9.jar:8.0.9+86+master.3cf110c]
		at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85) [modlauncher-8.0.9.jar:?]
		at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) [modlauncher-8.0.9.jar:?]
		at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) [modlauncher-8.0.9.jar:?]
		at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) [modlauncher-8.0.9.jar:?]
		at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) [modlauncher-8.0.9.jar:?]
		at java.lang.ClassLoader.loadClass(ClassLoader.java:357) [?:1.8.0_51]
		at java.lang.Class.forName0(Native Method) ~[?:1.8.0_51]
		at java.lang.Class.forName(Class.java:348) [?:1.8.0_51]
		at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.2.20.jar:36.2]
		at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$493/1256782634.call(Unknown Source) [forge-1.16.5-36.2.20.jar:36.2]
		at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?]
		at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?]
		at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?]
		at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?]
		at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?]

**Comment by BraveCaperCat** [comment]
> This does seem to be an us issue, You seem to have antique atlas somewhere its mixins don't apply. Like on the server side. I'm entirely sure if AA is _installable_ server-side. I'd guess from this thing. Anyway, I do see any of our code. Reopening.

**Comment by BraveCaperCat** [comment]
Is Correct

**Comment by BraveCaperCat** [comment]
Can you help me with The [Issue on modpack page](https://github.com/simibubi/Above-and-Beyond/issues/396)

**Comment by BraveCaperCat** [comment]
I'm confused, [Antique Atlas](https://www.curseforge.com/minecraft/mc-mods/antique-atlas) isn't in that modpack!

**Comment by Silfryi** [comment]
Fuck off with the spamming. I was _asleep_ for fucks sake. Anyway, about antique atlas. I saw MANY mixin errors and assumed one about AA was the error - since you **did not provide a modlist** (which is on you, not on me) for me to check against, I assumed it was AA. Since AA isn't in the pack then I think the _root_ cause is supplementaries. Either way there is NOTHING of our code in that stacktrace. We have no part here.
